# Generated by Django 4.1.1 on 2023-01-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0005_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(max_length=200),
        ),
    ]
