# Generated by Django 4.1.1 on 2023-01-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0007_language_course_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Certificate',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='Deadline',
            field=models.DateField(null=True),
        ),
    ]
